### ISSUE TITLE
ObserverAdapter

### ISSUE THREAD

**Issue by ReginFell** [partition/Dagger-Non-Configuration-Scope#1]
Hi Mateusz! 

Please, explain what the reason of using ObserverAdapter and muteOnComplete?

**Comment by ReginFell** [comment]
Oh, it is for Subjuct porpose, i got it. 

Thanks for amazing article

**Comment by henieek** [comment]
Yeah, exactly - I don't want subject get its state lost - otherwise cache wouldn't make any sense.
Looking forward for better ideas though!
